<!DOCTYPE KIRCHENGEMEINDE [
<!ELEMENT KIRCHENGEMEINDE (PERSONEN,VERANSTALTUNGEN)>
<!ELEMENT PERSONEN (PERSON*)>
<!ELEMENT PERSON (ID+,NAME+,TEL?,EMAIL?)>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT TEL (#PCDATA)>
<!ELEMENT EMAIL (#PCDATA)>
<!ELEMENT VERANSTALTUNGEN (VERANSTALTUNG*)>
<!ELEMENT VERANSTALTUNG (NR+,DATUM+,UHRZEIT+,ART+,INFO?,TEAM+)>
<!ELEMENT NR (#PCDATA)>
<!ELEMENT DATUM (#PCDATA)>
<!ELEMENT UHRZEIT (#PCDATA)>
<!ELEMENT ART (#PCDATA)>
<!ELEMENT INFO (#PCDATA)>
<!ELEMENT TEAM (#PCDATA)>
]>

<KIRCHENGEMEINDE>
    <PERSONEN>
        <PERSON>
            <ID></ID>
            <NAME>Pfarrerin Regina Weihe</NAME>
            <TEL></TEL>
            <EMAIL></EMAIL>
        </PERSON>
        <PERSON>
            <ID></ID>
            <NAME>Tom Zierenberg</NAME>
            <TEL></TEL>
            <EMAIL></EMAIL>
        </PERSON>
    </PERSONEN>
    <VERANSTALTUNGEN>
        <VERANSTALTUNG>
            <NR></NR>
            <DATUM></DATUM>
            <UHRZEIT></UHRZEIT>
            <ART></ART>
            <INFO></INFO>
            <TEAM></TEAM>
        </VERANSTALTUNG>
    </VERANSTALTUNGEN>
</KIRCHENGEMEINDE>
